export enum ActionTypes {
  MOVE_CELL = 'MOVE_CELL',
  DELETE_CELL = 'DELETE_CELL',
  INSERT_CELL = 'INSERT_CELL',
  UPDATE_CELL = 'UPDATE_CELL',
  CREATE_BUNDLE = 'CREATE_BUNDLE',
  COMPLETED_BUNDLE = 'COMPLETED_BUNDLE',
  FETCH_CELLS = 'FETCH_CELLS',
  FETCH_CELLS_COMPLETE = 'FETCH_CELLS_COMPLETE',
  FETCH_CELLS_ERROR = 'FETCH_CELLS_ERROR',
  SAVE_CELLS_ERROR = 'SAVE_CELLS_ERROR',
}
